on:
  workflow_dispatch:

name: Release

jobs:
  setup-variables:
    name: Setup variables
    runs-on: ubuntu-latest
    outputs:
      tag: ${{ steps.get-tag.outputs.tag }}
      matrix: ${{ steps.get-matrix.outputs.matrix }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Get tag
        id: get-tag
        run: |
          $version = (Get-Content ./i18n/vscode-language-pack-cs/package.json -Raw | ConvertFrom-Json).version
          Write-Host "tag: release/$version"
          Write-Host "::set-output name=tag::release/$version"
        shell: pwsh

      - name: Push tag
        id: tag_version
        uses: mathieudutour/github-tag-action@v5.5
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          custom_tag: ${{ steps.get-tag.ouputs.tag }}
          
      - name: Get matrix
        id: get-matrix
        run: |
          $obj = @{
            languagePack = Get-ChildItem i18n | ForEach-Object Name
          }
          Write-Host "::set-output name=matrix::$($obj | ConvertTo-Json -Depth 100 -Compress)"
        shell: pwsh

  build:
    name: Build
    needs: setup-variables
    runs-on: ubuntu-latest
    strategy:
      matrix: ${{fromJSON(needs.setup-variables.outputs.matrix)}}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: ${{ needs.setup-variables.outputs.tag }}

      - name: Generate Name
        run: node -e "console.log('PACKAGE_NAME=' + require('./i18n/${{ matrix.languagePack }}/package.json').name + '-v' + require('./i18n/${{ matrix.languagePack }}/package.json').version)" >> $GITHUB_ENV

      - name: Install
        run: cd ./i18n/${{ matrix.languagePack }} && npm i

      - name: Build Extension
        run: cd ./i18n/${{ matrix.languagePack }} && npx vsce package -o ${{ env.PACKAGE_NAME }}.vsix

      - name: Publish Test Artifact
        uses: actions/upload-artifact@v2
        with:
          name: ${{ env.PACKAGE_NAME }}.vsix
          path: ./i18n/${{ matrix.languagePack }}/${{ env.PACKAGE_NAME }}.vsix

  deploy:
    name: Publish
    needs:
      - build
      - setup-variables
    runs-on: ubuntu-latest
    strategy:
      matrix: ${{fromJSON(needs.setup-variables.outputs.matrix)}}
    environment: deploy
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: ${{ needs.setup-variables.outputs.tag }}

      - name: Generate Name
        run: node -e "console.log('PACKAGE_NAME=' + require('./i18n/${{ matrix.languagePack }}/package.json').name + '-v' + require('./i18n/${{ matrix.languagePack }}/package.json').version)" >> $GITHUB_ENV

      - name: Fetch Test Artifact
        uses: actions/download-artifact@v2
        with:
          name: ${{ env.PACKAGE_NAME }}.vsix

      - name: Verify access to publisher
        run: npx vsce verify-pat -p ${{ secrets.MARKETPLACE_PAT }} MS-CEINTL

      - name: Publish Extension
        run: npx vsce publish --packagePath ./${{ env.PACKAGE_NAME }}.vsix -p ${{ secrets.MARKETPLACE_PAT }}
  
  update-version:
    name: Update version
    needs: setup-variables
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Rev patch versions
        run: |
          Get-ChildItem i18n | ForEach-Object {
              cd $_.FullName
              npm version patch
          }
        shell: pwsh

      - name: Expose version
        run: node -e "console.log('PACKAGE_VERSION=' + require('./i18n/vscode-language-pack-cs/package.json').version)" >> $GITHUB_ENV

      - name: Create Pull Request on vscode-loc
        id: cpr
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.REPO_PAT }}
          title: Rev patch versions to ${{ env.PACKAGE_VERSION }}
          body: Automated changes
          branch: rev-patch-versions-to-${{ env.PACKAGE_VERSION }}
          commit-message: rev patch versions to ${{ env.PACKAGE_VERSION }}
          delete-branch: true

      - name: Enable Pull Request Automerge
        if: steps.cpr.outputs.pull-request-operation == 'created'
        uses: peter-evans/enable-pull-request-automerge@v1
        with:
          token: ${{ secrets.REPO_PAT }}
          pull-request-number: ${{ steps.cpr.outputs.pull-request-number }}
          merge-method: squash
